/**
 * Generates responsive `<picture>` element attributes for gallery images.
 * Priority: AVIF → WebP → original fallback.
 * AVIF is auto-generated by scripts/convert-to-avif.mjs at build time.
 */

export function getResponsivePictureAttrs(src: string, sizes?: string): {
  sources: Array<{ type: string; srcSet: string; sizes?: string }>;
  fallback: { src: string; srcSet?: string; sizes?: string };
} {
  if (!sizes || !src.startsWith("/images/gallery/")) {
    return {
      sources: [],
      fallback: { src },
    };
  }

  const base = src.replace(/\?.*$/, "");
  const version = src.includes("?") ? src.slice(src.indexOf("?")) : "";
  const fileName = base.split("/").pop() || "";
  const avifName = fileName.replace(/\.webp$/, ".avif");

  const avifSrcSet = [
    `/images/gallery/640/${avifName}${version} 640w`,
    `/images/gallery/960/${avifName}${version} 960w`,
    `/images/gallery/${avifName}${version} 1200w`,
  ].join(", ");

  const webpSrcSet = [
    `/images/gallery/640/${fileName}${version} 640w`,
    `/images/gallery/960/${fileName}${version} 960w`,
    `${base}${version} 1200w`,
  ].join(", ");

  return {
    sources: [
      { type: "image/avif", srcSet: avifSrcSet, sizes },
      { type: "image/webp", srcSet: webpSrcSet, sizes },
    ],
    fallback: { src, srcSet: webpSrcSet, sizes },
  };
}
