import { getResponsiveImageDirectory, getResponsiveImageSourceWidth } from "./responsive-image";

/**
 * Generates responsive `<picture>` element attributes for local editorial images.
 * Priority: AVIF → WebP → original fallback.
 * AVIF is auto-generated by scripts/convert-to-avif.mjs at build time.
 */

export function getResponsivePictureAttrs(src: string, sizes?: string): {
  sources: Array<{ type: string; srcSet: string; sizes?: string }>;
  fallback: { src: string; srcSet?: string; sizes?: string };
} {
  const directory = getResponsiveImageDirectory(src);
  if (!sizes || !directory) {
    return {
      sources: [],
      fallback: { src },
    };
  }

  const base = src.replace(/\?.*$/, "");
  const version = src.includes("?") ? src.slice(src.indexOf("?")) : "";
  const fileName = base.split("/").pop() || "";
  const avifName = fileName.replace(/\.webp$/, ".avif");
  const sourceWidth = getResponsiveImageSourceWidth(src);

  const avifSrcSet = [
    `${directory}640/${avifName}${version} 640w`,
    `${directory}960/${avifName}${version} 960w`,
    `${directory}${avifName}${version} ${sourceWidth}w`,
  ].join(", ");

  const webpSrcSet = [
    `${directory}640/${fileName}${version} 640w`,
    `${directory}960/${fileName}${version} 960w`,
    `${base}${version} ${sourceWidth}w`,
  ].join(", ");

  return {
    sources: [
      { type: "image/avif", srcSet: avifSrcSet, sizes },
      { type: "image/webp", srcSet: webpSrcSet, sizes },
    ],
    fallback: { src, srcSet: webpSrcSet, sizes },
  };
}
