name = "naihuangbao-photography"
pages_build_output_dir = "dist"
compatibility_date = "2026-04-27"

[[r2_buckets]]
binding = "PHOTO_BUCKET"
bucket_name = "naihuangbao-photography"

[[d1_databases]]
binding = "DB"
database_name = "naihuangbao-photography"
database_id = "e052d4a9-d8aa-4a34-aee0-c328ac2e23dc"
