-- ============================================
-- 奶黄包摄影 - 种子数据
-- 课程 / 预设 / 工作坊 / 周边产品 / P图服务
-- ============================================

-- ── 课程 ──
INSERT INTO courses (id, title, title_en, description, description_en, cover_image_url, category, difficulty, duration_minutes, sort_order, published, created_at, updated_at) VALUES
('course-001', '人像摄影入门：从零开始', 'Portrait Photography Basics', '从相机设置到构图基础，带你迈出人像摄影第一步。适合完全零基础的摄影爱好者。', 'From camera settings to composition basics, take your first step in portrait photography.', '/images/courses/course-basics.webp', 'beginner', 'beginner', 45, 1, 1, datetime('now'), datetime('now')),
('course-002', '自然光人像：南京外拍实战', 'Natural Light Portraits: Nanjing Outdoor Shoot', '以南京经典场景（玄武湖、颐和路、紫金山）为例，实战讲解自然光人像拍摄技巧。', 'Using Nanjing classic locations as examples, practical natural light portrait techniques.', '/images/courses/course-outdoor.webp', 'beginner', 'intermediate', 60, 2, 1, datetime('now'), datetime('now')),
('course-003', '胶片感人像后期调色', 'Film Look Portrait Post-Processing', '从 Lightroom 基础到高级调色思路，打造柔和胶片感的人像作品。', 'From Lightroom basics to advanced color grading, create soft film-look portraits.', '/images/courses/course-lr-color.webp', 'post-processing', 'intermediate', 50, 3, 1, datetime('now'), datetime('now')),
('course-004', '摆姿引导：让模特自然放松', 'Posing Guide: Making Models Feel Natural', '站姿、坐姿、互动引导的完整方法论，让被拍者放松自然。', 'Complete methodology for standing, sitting, and interaction posing.', '/images/courses/course-posing.webp', 'posing', 'beginner', 40, 4, 1, datetime('now'), datetime('now')),
('course-005', '进阶：夜景与弱光人像', 'Advanced: Night & Low-Light Portraits', '高感光度运用、补光技巧、长曝光人像，突破弱光环境限制。', 'High ISO usage, fill light techniques, long exposure portraits.', '/images/courses/course-night.webp', 'advanced', 'advanced', 55, 5, 1, datetime('now'), datetime('now')),
('course-006', 'Photoshop 人像精修全流程', 'Photoshop Portrait Retouching Workflow', '磨皮、液化、调色、锐化的完整精修流程，打造商业级人像作品。', 'Complete retouching workflow: skin smoothing, liquify, color grading, sharpening.', '/images/courses/course-ps-retouch.webp', 'post-processing', 'advanced', 65, 6, 1, datetime('now'), datetime('now'));

-- ── 预设/资源包 ──
INSERT INTO presets (id, name, name_en, description, description_en, category, preview_images, download_url, price_display, featured, download_count, created_at, updated_at) VALUES
('preset-001', '柔和胶片感 LR 预设', 'Soft Film Look Lightroom Presets', '10 个精心调校的预设，适合日系、清新、日常风格的人像写真。一键套用即可获得柔和胶片质感。', '10 carefully crafted presets for Japanese, fresh, and daily life portrait styles.', 'lightroom', '["/images/presets/preset-film-preview.webp"]', '/downloads/preset-film-look.zip', '¥29', 1, 128, datetime('now'), datetime('now')),
('preset-002', '复古暖调 LR 预设', 'Vintage Warm Tone Lightroom Presets', '8 个复古暖调预设，适合秋冬季节、咖啡厅、老街等温暖场景。', '8 vintage warm tone presets for autumn, cafe, and old street scenes.', 'lightroom', '["/images/presets/preset-vintage-preview.webp"]', '/downloads/preset-vintage-warm.zip', '¥29', 0, 86, datetime('now'), datetime('now')),
('preset-003', '人像精修 PS 动作包', 'Portrait Retouching Photoshop Actions', '一键磨皮、美白、锐化动作，大幅提升修图效率。包含 5 个常用动作。', 'One-click skin smoothing, whitening, and sharpening actions.', 'photoshop', '["/images/presets/preset-ps-preview.webp"]', '/downloads/preset-ps-actions.zip', '¥39', 1, 64, datetime('now'), datetime('now')),
('preset-004', '电影感视频 LUT 包', 'Cinematic Video LUT Pack', '6 个电影感 LUT，适合 Vlog、短视频、婚礼视频调色。', '6 cinematic LUTs for vlogs, short films, and wedding videos.', 'luts', '["/images/presets/preset-lut-preview.webp"]', '/downloads/preset-cinematic-lut.zip', '¥19', 0, 42, datetime('now'), datetime('now')),
('preset-005', '高清人像笔刷套装', 'HD Portrait Brush Set', '20 个精修笔刷，包含磨皮、光影、纹理等类型。', '20 retouching brushes including skin, light, and texture types.', 'photoshop', '["/images/presets/preset-brush-preview.webp"]', '/downloads/preset-brushes.zip', '¥15', 0, 35, datetime('now'), datetime('now')),
('preset-006', '证件照/形象照 LR 预设', 'ID Photo Lightroom Presets', '8 个快速出片预设，专为证件照、形象照、简历照片设计。', '8 quick presets designed for ID photos, profile pictures, and resume photos.', 'lightroom', '["/images/presets/preset-id-preview.webp"]', '/downloads/preset-id-photo.zip', '¥19', 0, 53, datetime('now'), datetime('now')),
('preset-007', '日系清新 LR 预设', 'Japanese Fresh Lightroom Presets', '12 个明亮通透的日系预设，适合樱花、校园、清新风格拍摄。', '12 bright and transparent Japanese presets for cherry blossom and campus shoots.', 'lightroom', '["/images/presets/preset-japanese-preview.webp"]', '/downloads/preset-japanese-fresh.zip', '¥29', 1, 97, datetime('now'), datetime('now')),
('preset-008', '婚纱/情侣 LR 预设', 'Wedding Couple Lightroom Presets', '10 个浪漫暖调预设，专为婚纱照、情侣写真、纪念日照设计。', '10 romantic warm presets for wedding, couple, and anniversary photos.', 'lightroom', '["/images/presets/preset-wedding-preview.webp"]', '/downloads/preset-wedding-couple.zip', '¥39', 0, 71, datetime('now'), datetime('now'));

-- ── 工作坊/活动 ──
INSERT INTO workshops (id, title, title_en, description, description_en, cover_image_url, event_date, event_time, location, max_participants, current_participants, price_display, status, created_at, updated_at) VALUES
('ws-001', '玄武湖人像外拍实战', 'Xuanwu Lake Outdoor Portrait Shoot', '在南京玄武湖公园进行户外人像拍摄实战，全程指导构图、光线、摆姿。适合初级到中级摄影爱好者。', 'Outdoor portrait shoot at Xuanwu Lake Park with full guidance on composition, lighting, and posing.', '/images/workshops/ws-xuanwu.webp', '2026-06-15', '14:00-17:00', '玄武湖公园·解放门', 12, 5, '¥199/人', 'upcoming', datetime('now'), datetime('now')),
('ws-002', 'Lightroom 调色工作坊', 'Lightroom Color Grading Workshop', '线上直播教学，从调色思路到实操演示，学会打造属于自己的预设风格。', 'Live online teaching, from color grading theory to practical demonstration.', '/images/workshops/ws-lr-workshop.webp', '2026-06-22', '19:00-21:00', '线上直播（腾讯会议）', 30, 12, '¥99/人', 'upcoming', datetime('now'), datetime('now')),
('ws-003', '紫金山日落人像拍摄', 'Purple Mountain Sunset Portrait Shoot', '在紫金山拍摄日落人像，捕捉黄金时刻的光影。限 10 人小班教学。', 'Sunset portrait shoot at Purple Mountain, capturing golden hour light.', '/images/workshops/ws-sunset.webp', '2026-07-06', '16:00-19:00', '紫金山·天文台路', 10, 3, '¥249/人', 'upcoming', datetime('now'), datetime('now')),
('ws-004', '摄影作品互评沙龙', 'Photography Critique Salon', '定期摄影主题聚会，带你的作品来，一起交流、互评、进步。免费参加。', 'Regular photography meetup. Bring your work for discussion and feedback.', '/images/workshops/ws-salon.webp', '2026-07-13', '14:00-16:00', '仙林·咖啡厅（具体地址另行通知）', 15, 0, '免费', 'upcoming', datetime('now'), datetime('now'));

-- ── 周边产品（含P图服务） ──
INSERT INTO merchandise (id, name, name_en, description, description_en, images, category, price_display, available, created_at, updated_at) VALUES
('merch-001', '定制写真相册（20P）', 'Custom Portrait Album (20 Pages)', '高清冲印精装相册，20 页精美排版，适合珍藏每一次拍摄回忆。', 'HD printed hardcover album, 20 pages of beautifully laid out photos.', '["/images/merch/album-preview.webp"]', 'album', '¥128', 1, datetime('now'), datetime('now')),
('merch-002', '人像明信片套装（10张）', 'Portrait Postcard Set (10 Cards)', '哑光材质精美明信片，10 张不同风格人像作品，适合收藏或赠送。', 'Matte finish postcards, 10 different portrait works for collection or gifting.', '["/images/merch/postcard-preview.webp"]', 'postcard', '¥39', 1, datetime('now'), datetime('now')),
('merch-003', '人像摄影作品冲印', 'Portrait Photo Print', 'A4 尺寸高清艺术微喷，使用专业相纸，色彩还原精准。', 'A4 HD art giclée print on professional photo paper.', '["/images/merch/print-preview.webp"]', 'print', '¥15/张', 1, datetime('now'), datetime('now')),
('merch-004', '品牌 T 恤', 'Brand T-Shirt', '摄影师联名款 T 恤，简约设计，纯棉材质。', 'Photographer collaboration T-shirt, minimalist design, 100% cotton.', '["/images/merch/tshirt-preview.webp"]', 'other', '¥89', 1, datetime('now'), datetime('now')),
('merch-005', '品牌帆布包', 'Brand Canvas Bag', '摄影主题设计帆布包，大容量，日常通勤实用。', 'Photography-themed canvas bag, large capacity, practical for daily use.', '["/images/merch/bag-preview.webp"]', 'other', '¥59', 1, datetime('now'), datetime('now')),
('merch-006', '器材租赁：索尼 A7C II', 'Equipment Rental: Sony A7C II', '含机身 + 适马 28-70mm 镜头，适合体验高端器材。需提前预约。', 'Camera body + Sigma 28-70mm lens. Reservation required.', '["/images/merch/rental-preview.webp"]', 'other', '¥99/天', 1, datetime('now'), datetime('now')),
('merch-007', '单张精修', 'Single Photo Retouch', '基础磨皮 + 调色，适合日常写真照片精修。', 'Basic skin smoothing + color grading for everyday portrait photos.', '["/images/merch/retouch-single.webp"]', 'other', '¥19/张', 1, datetime('now'), datetime('now')),
('merch-008', '深度精修', 'Deep Photo Retouch', '精细磨皮 + 液化 + 调色，适合商业级人像作品。', 'Detailed skin smoothing + liquify + color grading for commercial portraits.', '["/images/merch/retouch-deep.webp"]', 'other', '¥39/张', 1, datetime('now'), datetime('now')),
('merch-009', '证件照精修', 'ID Photo Retouch', '证件照/形象照专用精修，快速出片，符合证件要求。', 'Specialized retouching for ID and profile photos.', '["/images/merch/retouch-id.webp"]', 'other', '¥29/张', 1, datetime('now'), datetime('now')),
('merch-010', '批量调色（10张起）', 'Batch Color Grading (10+)', '统一风格调色，适合写真套图、活动照片批量处理。', 'Unified style color grading for portrait sets and event photos.', '["/images/merch/retouch-batch.webp"]', 'other', '¥10/张', 1, datetime('now'), datetime('now'));
